server:
  port: 8088

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/nutrient
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always  #data.sql

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # sql 로그에서 확인
        # show_sql: true
    defer-datasource-initialization: true #data.sql

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace # binding parameter 확인 (p6spy 로 대체)

jwt:
  token:
    #header: X-AUTH
    #issuer: nutrient
    secret: NUTRIENT_SECRET_TOKEN
    expiry-seconds: 3600
