server:
  port: 8088

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/nutrient
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true # sql 로그에서 확인
        # show_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace # binding parameter 확인 (p6spy 로 대체)